
//USER
export const USER_LOGIN = "USER_LOGIN";
export const USER_REGISTER = "USER_REGISTER";
export const USER_LOGIN_PENDING = "USER_LOGIN_PENDING";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";
export const USER_LOGIN_FULFILLED = "USER_LOGIN_FULFILLED";

//MANAGED_USER
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SELECTED = "REGISTER_USER_SELECTED";
export const REGISTER_USER_UN_SELECTED = "REGISTER_USER_UN_SELECTED";
export const REGISTER_USER_PENDING = "REGISTER_USER_PENDING";
export const REGISTER_USER_FULFILLED = "REGISTER_USER_FULFILLED";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const GET_USER =  "GET_USER";
export const GET_USER_PENDING =  "GET_USER_PENDING";
export const GET_USER_FULFILLED =  "GET_USER_FULFILLED";
export const GET_USER_ERROR =  "GET_USER_ERROR";

export const GET_USER_LIST =  "GET_USER_LIST";
export const GET_USER_LIST_PENDING =  "GET_USER_LIST_PENDING";
export const GET_USER_LIST_FULFILLED =  "GET_USER_LIST_FULFILLED";
export const GET_USER_LIST_ERROR =  "GET_USER_LIST_ERROR";

export const EDIT_USER =  "EDIT_USER";
export const CLEAR_USER = "CLEAR_USER";
export const EDIT_USER_SELECTED =  "EDIT_USER_SELECTED";
export const EDIT_USER_UN_SELECTED =  "EDIT_USER_UN_SELECTED";
export const EDIT_USER_PENDING =  "EDIT_USER_PENDING";
export const EDIT_USER_FULFILLED =  "EDIT_USER_FULFILLED";
export const EDIT_USER_ERROR =  "EDIT_USER_ERROR";
export const EDIT_USER_LOCAL_NAME =  "EDIT_USER_LOCAL_NAME";
export const EDIT_USER_LOCAL_SURANAME =  "EDIT_USER_LOCAL_SURANAME";
export const EDIT_USER_LOCAL_EMAIL =  "EDIT_USER_LOCAL_EMAIL";
export const EDIT_USER_LOCAL_PASSWORD =  "EDIT_USER_LOCAL_PASSWORD";
export const EDIT_USER_LOCAL_ROLES = "EDIT_USER_LOCAL_ROLES";
export const EDIT_USER_SAVE =  "EDIT_USER_SAVE";

export const PERMISSIONS_CHANGE_PENDING =  "PERMISSIONS_CHANGE_PENDING";
export const PERMISSIONS_CHANGE_FULFILLED =  "PERMISSIONS_CHANGE_FULFILLED";
export const PERMISSIONS_CHANGE_ERROR =  "PERMISSIONS_CHANGE_ERROR";
export const PERMISSIONS_CHANGE_FETCHED =  "PERMISSIONS_CHANGE";

export const PERMISSIONS_REQUEST_PENDING =  "PERMISSIONS_REQUEST_PENDING";
export const PERMISSIONS_REQUEST_FULFILLED =  "PERMISSIONS_REQUEST_FULFILLED";
export const PERMISSIONS_REQUEST_ERROR =  "PERMISSIONS_REQUEST_ERROR";
export const PERMISSIONS_REQUEST_FETCHED =  "PERMISSIONS_REQUEST";