
//USER
export const USER_LOGIN = "USER_LOGIN";
export const USER_REGISTER = "USER_REGISTER";
export const USER_LOGIN_PENDING = "USER_LOGIN_PENDING";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";
export const USER_LOGIN_FULFILLED = "USER_LOGIN_FULFILLED";

//MANAGED_USER
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_PENDING = "REGISTER_USER_PENDING";
export const REGISTER_USER_FULFILLED = "REGISTER_USER_FULFILLED";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const GET_USER =  "GET_USER";
export const GET_USER_PENDING =  "GET_USER_PENDING";
export const GET_USER_FULFILLED =  "GET_USER_FULFILLED";
export const GET_USER_ERROR =  "GET_USER_ERROR";

export const GET_USER_LIST =  "GET_USER_LIST";
export const GET_USER_LIST_PENDING =  "GET_USER_LIST_PENDING";
export const GET_USER_LIST_FULFILLED =  "GET_USER_LIST_FULFILLED";
export const GET_USER_LIST_ERROR =  "GET_USER_LIST_ERROR";
