
//PODSTAWOWE
export const EDIT = "EDYTUJ";
export const SAVE = "ZAPISZ";
export const ADD = "DODAJ";
export const CANCEL = "ANULUJ";
export const JUSTIFY = "WYJAŚNIJ"

//USERS MANAGEMENT UI
export const EMPLOEE_ID = "ID PRACOWNIKA";
export const EMPLOEE_NAME = "IMIĘ";
export const EMPLOEE_SURNAME = "NAZWISKO";
export const EMPLOEE_EMAIL = "EMAIL";
export const EMPLOEE_ROLES = "ROLE";
export const EMPLOEE_PASSWORD = "HASŁO";
export const EMPLOEE_ROLES_HINT = "TA KOLUMNA NIE ZAPEWNIA SORTOWANIA";
export const USER_MANAGEMENT_PAGE = "ZARZĄDZANIE UŻYTKOWNIKAMI";
export const CONFIRM_YOUR_PASSWORD = "POWTÓRZ HASŁO"

//INFO
export const NO_JUSTIFICATION_SELECTED_TO_SHOW_CHANGES_FOR = "WYBIERZ WYJAŚNIENIE ABY WYŚWIETLIĆ ZMIANY UPRAWNIEŃ JAKICH DOTYCZY"
export const NO_JUSTIFICATION_NO_HISTORY = "WYBIERZ WYJAŚNIENIE ABY WYŚWIETLIĆ JEGO HISTORIE"
export const USER_MENU = "MENU UŻYTKOWNIKA"
//ROLE
export const ROLE_ADMIN = "ADMIN UŻYTKOWNIKÓW";
export const ROLE_REVIEWER = "KONTROLER";
export const ROLE_REVIEWER_MANAGER = "MANAGER KONTROLERA";
export const ROLE_REVIEWED_ISA = "KONTROLOWANY ADMIN";

//USER LOGIN
export const LOGIN_FAILED_SNACKBAR = "NIEPRAWIDŁOWY EMAIL LUB HASŁO. LOGOWANIE NIEUDANE!";
export const LOGIN_SUCCESS_SNACKBAR = "SUKCES LOGOWANIA";
export const ENTER_EMAIL_ADRESS = "WPISZ ADRES EMAIL";
export const ENTER_PASSWORD = "WPISZ HASŁO";
export const LOGIN = "ZALOGUJ";
export const LOGIN_PAGE = "LOGOWANIE";
export const LOGOUT =  "WYLOGUJ"

//WYSZUKIWANIE APLIKACJI
export const APPLICATION_SEARCH = "WYSZUKAJ APLIKACJĘ";
export const ENTER_APPLICATION_NAME = "WPISZ NAZWĘ";
export const SEARCH = "SZUKAJ";
//PRZEGLĄD
export const REVIEW_PAGE ="PRZEGLĄD";
export const EVENT_DATE = "DATA I CZAS";
export const SUBJECT_EMPLOYEE_ID = "ZMIENIONO UPRAWNIENIA DLA";
export const ISA_EMPLOYEE_ID = "DOKONAŁ ZMIANY";
export const APPLICATION_NAME = "NAZWA APLIKACJI";
export const APPLICATION_INVENTORY_NO = "NR INWENTARZOWY APLIKACJI";
export const APPLICATION_ROLE_NAME = "NAZWA ROLI";
export const EVENT_ID = "ID ZDARZENIA";
export const REVIEW_CHANGES_FOR = "PRZEGLĄD ZMIAN DLA APLIKACJI:";
export const PERMISSION_CHANGES = "ZMIANY UPRAWNIEŃ";
export const PERMISSION_REQUESTS = "ZAMÓWIENIA";
export const SELECTED_ITEMS = "WYBRANE ELEMENTY";
export const REQUEST = "WYBRANE ZAMÓWIENIE";
export const NO_REQUEST_SELECTED = "BRAK WYBRANEGO ZAMÓWIENIA";
export const NO_CHANGES_SELECTED = "BRAK WYBRANYCH ZMIAN";
export const CHANGES = "WYBRANE ZMIANY";
//PRZEGLĄD ZMIANA
export const ADDITIONAL_DETAILS = "DODATKOWE INFORMACJE";
//PRZEGLĄD ZAMÓWIENIE
export const REQUEST_NUMBER = "NUMER ZAMÓWIENIA";
export const APPROVER_EMPLOYEE_ID = "AKCEPTOWAŁ";
export const REQUEST_STATUS = "STATUS ZAMÓWIENIA";
//PRZEGLĄD ALERTY
export const ALERT_UNMATCHED_ISA = "WPISANIE ZMIAN WYKONANYCH PRZEZ RÓŻNYCH ADMINISTRATORÓW DO JEDNEGO WYJAŚNIENIENIA NIE JEST MOŻLIWE. KOLUMNA DOKONAŁ ZMIAN MUSI ZAWIERĆ JEDNAKOWĄ WARTOŚĆ"
//WYJAŚNIENIE
export const JUSTIFICATION_PAGE ="WYJAŚNIANIE";
export const PENDING_JUSTIFICATION_LIST = "LISTA OCZEKUJĄCYCH WYJAŚNIEŃ"
export const JUSTIFICATION_ID ="ID WYJAŚNIENIA";
export const CURENT_STATUS ="OBECNY STATUS";
export const LAST_COMMENT ="OSTATNI KOMENTARZ";
export const ASSIGNED_REVIEWER ="PRZYPISANY KONTROLER";
export const ASSIGNED_ISA ="PRZYPISANY ADMINISTRATOR";
export const CREATE_DATE ="DATA UTWORZENIA";
export const MODIFY_DATE ="DATA MODYFIKACJI";
export const ABOUT_PERMISSION_CHANGES = "WYBRANE WYJAŚNIENIE DOTYCZY ZMIAN UPRAWNIEŃ";
export const COMMENT = "KOMENTARZ";
export const PENDING_ADMIN = "OCZEKUJE NA ADMINA";
export const PENDING_REVIEW = "OCZEKUJE NA KONTROLERA";
export const COMPLETE = "ZAKOŃCZONE";
export const UNKNOWN = "NIEZNANY";
export const SELECT_NEW_STATUS = "WYBIERZ NOWY STATUS";
export const JUSTIFICATION_HISTORY_LIST = "HISTORIA WYBRANEGO WYJAŚNIENIA";
export const STATUS_UPDATE_DATE = "DATA UTWORZENIA STATUSU";
export const STATUS_UPDATE_ID = "ID ZMIANY";
export const CHENGED_BY = "ZMIANY DOKONAŁ";
export const NEW_STAUS = "NOWY STATUS";
export const PREVIOUS_STATUS = "POPRZEDNI STATUS";
export const PREVIOUS_COMMENT = "POPRZEDNI KOMENTARZ";
export const NEW_COMMENT = "NOWY KOMENTARZ";
export const NO_JUSTIFICATION_HISTORY_FIRST_QUERY = "BRAK HISTORII DO WYŚWIETLENIA. PIERWSZE ZAPYTANIE ODNOŚNIE ZMIANY";
export const PROVIDE_JUSTIFICATION ="UDZIEL WYJAśNIENIA"

//WALIDACJA
export const ENTER_YOUR_PASSWORD = "WPISZ HASŁO";
export const PASSWORD_IS_REQUIRED = "HASŁO JEST WYMAGANE";
export const PASSWORD_MINIMUM_LENGHT = "HASŁO MUSI MIEĆ MIN. 7 ZNAKÓW";
export const ENTER_YOUR_EMAIL = "WPISZ EMAIL";
export const EMAIL_IS_REQUIRED = "EMAIL JEST WYMAGANY";
export const EMAIL_SHOULD_BE_VALID = "EMAIL MUSI BYĆ POPRAWNY";
export const ENTER_YOUR_NAME = "WPISZ IMIĘ";
export const NAME_IS_REQUIRED = "IMIĘ JEST WYMAGANE";
export const NAME_MINIMUM_LENGHT = "IMIĘ MUSI MIEĆ MINIMUM 3 ZANKI";
export const ENTER_YOUR_SURNAME = "WPISZ NAZWISKO";
export const SURNAME_IS_REQUIRED = "NAZWISKO JEST WYMAGANE";
export const SURNAME_MINIMUM_LENGHT = "NAZWISKO MUSI MIEĆ MINIMUM 3 ZANKI";
export const INVALID_STATUS = "NIEPRAWIDLOWY LUB NIEWYBRANY STATUS";
export const STATUS_IS_REQUIRED = "STATUS JEST WYMAGANY";
export const CONFIRM_PASSWORD_IS_REQUIRED = "MUSISZ POWTÓRZYĆ HASŁO";
export const PASSWORDS_DO_NOT_MATCH = "HASŁA NIE SĄ JEDNAKOWE";

//WALIDACJA WYJAŚNIEŃ
export const COMMENT_MINIMUM_LENGHT = "WYJASNIENIE MUSI MIEĆ PRZYNAJMNIEJ 20 ZNAKÓW";
export const COMMENT_IS_REQUIRED = "KOMENTARZ JEST WYMAGANY";





