//USERS MANAGEMENT UI
export const EMPLOEE_ID = "ID PRACOWNIKA";
export const EMPLOEE_NAME = "IMIĘ";
export const EMPLOEE_SURNAME = "NAZWISKO";
export const EMPLOEE_EMAIL = "EMAIL";
export const EMPLOEE_ROLES = "ROLE";
export const EMPLOEE_PASSWORD = "HASŁO";
export const EMPLOEE_ROLES_HINT = "TA KOLUMNA NIE ZAPEWNIA SORTOWANIA";
export const USER_MANAGEMENT_PAGE = "ZARZĄDZANIE UŻYTKOWNIKAMI";
export const EDIT = "EDYTUJ";
export const SAVE = "ZAPISZ";
export const ADD = "DODAJ";
export const CANCEL = "ANULUJ";


//ROLES
export const ROLE_ADMIN = "ADMIN UŻYTKOWNIKÓW";
export const ROLE_REVIEWER = "KONTROLER";
export const ROLE_REVIEWER_MANAGER = "MANAGER KONTROLERA";
export const ROLE_REVIEWED_ISA = "KONTROLOWANY ADMIN";

//USER LOGIN
export const LOGIN_FAILED_SNACKBAR = "NIEPRAWIDŁOWY EMAIL LUB HASŁO. LOGOWANIE NIEUDANE!";
export const LOGIN_SUCCESS_SNACKBAR = "SUKCES LOGOWANIA";
export const ENTER_EMAIL_ADRESS = "WPISZ ADRES EMAIL";
export const ENTER_PASSWORD = "WPISZ HASŁO";
export const LOGIN = "ZALOGUJ";
export const LOGIN_PAGE = "LOGOWANIE";

//WYSZUKIWANIE APLIKACJI
export const APPLICATION_SEARCH = "WYSZUKAJ APPLIKACJE";
export const ENTER_APPLICATION_NAME = "WPISZ NAZWĘ";
export const SEARCH = "SZUKAJ";

//PRZEGLĄD
export const REVIEW_PAGE ="PRZEGLĄD";


//WYJAŚNIENIE
export const JUSTIFICATION_PAGE ="WYJAŚNIENIE";

//WALIDACJA
export const ENTER_YOUR_PASSWORD = "WPISZ HASŁO";
export const PASSWORD_IS_REQUIRED = "HASŁO JEST WYMAGANE";
export const PASSWORD_MINIMUM_LENGHT = "HASŁO MUSI MIEĆ MIN. 7 ZNAKÓW";

export const ENTER_YOUR_EMAIL = "WPISZ EMAIL";
export const EMAIL_IS_REQUIRED = "EMAIL JEST WYMAGANY";
export const EMAIL_SHOULD_BE_VALID = "EMAIL MUSI BYĆ POPRAWNY";

export const ENTER_YOUR_NAME = "WPISZ IMIĘ";
export const NAME_IS_REQUIRED = "IMIĘ JEST WYMAGANE";
export const NAME_MINIMUM_LENGHT = "IMIĘ MUSI MIEĆ MINIMUM 3 ZANKI";

export const ENTER_YOUR_SURNAME = "WPISZ NAZWISKO";
export const SURNAME_IS_REQUIRED = "NAZWISKO JEST WYMAGANE";
export const SURNAME_MINIMUM_LENGHT = "NAZWISKO MUSI MIĘĆ MINIMUM 3 ZNAKI";