//USERS MANAGEMENT UI
export const EMPLOEE_ID = "ID PRACOWNIKA";
export const EMPLOEE_NAME = "IMIĘ";
export const EMPLOEE_SURNAME = "NAZWISKO";
export const EMPLOEE_EMAIL = "EMAIL";
export const EMPLOEE_ROLES = "ROLE";
export const EMPLOEE_PASSWORD = "HASŁO";
export const EMPLOEE_ROLES_HINT = "TA KOLUMNA NIE ZAPEWNIA SORTOWANIA";
export const USER_MANAGEMENT_PAGE = "ZARZĄDZANIE UŻYTKOWNIKAMI";

//ROLES
export const ROLE_ADMIN = "ADMIN UŻYTKOWNIKÓW";
export const ROLE_REVIEWER = "KONTROLER";
export const ROLE_REVIEWER_MANAGER = "MANAGER KONTROLERA";
export const ROLE_REVIEWED_ISA = "KONTROLOWANY ADMIN";

//USER LOGIN
export const LOGIN_FAILED_SNACKBAR = "NIEPRAWIDŁOWY EMAIL LUB HASŁO. LOGOWANIE NIEUDANE!";
export const LOGIN_SUCCESS_SNACKBAR = "SUKCES LOGOWANIA";
export const ENTER_EMAIL_ADRESS = "WPISZ ADRES EMAIL";
export const ENTER_PASSWORD = "WPISZ HASŁO";
export const LOGIN = "ZALOGUJ";
export const LOGIN_PAGE = "LOGOWANIE";

//WYSZUKIWANIE APLIKACJI
export const APPLICATION_SEARCH = "WYSZUKAJ APPLIKACJE";
export const ENTER_APPLICATION_NAME = "WPISZ NAZWĘ";
export const SEARCH = "SZUKAJ";

//PRZEGLĄD
export const REVIEW_PAGE ="PRZEGLĄD";


//WYJAŚNIENIE
export const JUSTIFICATION_PAGE ="WYJAŚNIENIE";